create extension if not exists pgcrypto;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 100),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  "SKU" text not null unique,
  name text not null check (char_length(trim(name)) between 1 and 200),
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  discount_price numeric(12,2) not null default 0 check (discount_price >= 0),
  category text,
  stock integer not null default 0 check (stock >= 0),
  barcode text unique,
  image text,
  images jsonb not null default '[]'::jsonb check (jsonb_typeof(images) = 'array'),
  is_bestseller boolean not null default false,
  campaign_start_date timestamptz,
  campaign_end_date timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (campaign_end_date is null or campaign_start_date is null or campaign_end_date > campaign_start_date)
);

create table if not exists public.hero_slides (
  id bigint generated by default as identity primary key,
  image_url text not null,
  title text,
  subtitle text,
  category_slug text,
  created_at timestamptz not null default now()
);

create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  name text not null,
  discount_percent numeric(5,2) not null check (discount_percent > 0 and discount_percent < 100),
  start_date timestamptz not null,
  end_date timestamptz not null,
  product_ids jsonb not null default '[]'::jsonb check (jsonb_typeof(product_ids) = 'array'),
  created_at timestamptz not null default now(),
  check (end_date > start_date)
);

create table if not exists public.customers (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  first_name text,
  last_name text,
  full_name text,
  phone text,
  gender text,
  birth_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  first_name text not null,
  last_name text not null,
  phone text not null,
  city text not null,
  district text not null,
  neighborhood text not null,
  full_address text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists addresses_one_default_per_user
  on public.addresses(user_id) where is_default = true;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_no text not null unique,
  merchant_oid text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  user_email text not null,
  items jsonb not null check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) > 0),
  total_amount numeric(12,2) not null check (total_amount > 0),
  shipping_address jsonb not null,
  status text not null,
  payment_provider text not null default 'paytr',
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','failed','partially_refunded','refunded')),
  paytr_total_amount bigint not null check (paytr_total_amount > 0),
  paid_at timestamptz,
  failed_reason text,
  shipping_carrier text,
  tracking_number text,
  coupon_code text,
  coupon_discount_amount numeric(12,2) check (coupon_discount_amount is null or coupon_discount_amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_user_created_idx on public.orders(user_id, created_at desc);
create index if not exists orders_payment_created_idx on public.orders(payment_status, created_at desc);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text not null,
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 3 and 2000),
  images jsonb not null default '[]'::jsonb check (jsonb_typeof(images) = 'array'),
  is_approved boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create index if not exists reviews_product_approved_idx on public.reviews(product_id, is_approved);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text not null,
  question text not null check (char_length(trim(question)) between 3 and 2000),
  answer text,
  is_approved boolean not null default false,
  answered_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_email text not null,
  message text not null check (char_length(trim(message)) between 1 and 2000),
  answer text,
  answered_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.product_views (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  discount_type text not null check (discount_type in ('percent','fixed')),
  discount_value numeric(12,2) not null check (discount_value > 0),
  min_order_amount numeric(12,2) not null default 0 check (min_order_amount >= 0),
  max_discount_amount numeric(12,2),
  starts_at timestamptz,
  ends_at timestamptz,
  usage_limit_total integer,
  usage_limit_per_user integer not null default 1 check (usage_limit_per_user > 0),
  used_count integer not null default 0 check (used_count >= 0),
  is_active boolean not null default true,
  is_member_only boolean not null default true,
  created_at timestamptz not null default now(),
  check (ends_at is null or starts_at is null or ends_at > starts_at)
);

create table if not exists public.coupon_usages (
  id bigint generated by default as identity primary key,
  coupon_id bigint not null references public.coupons(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  coupon_code text not null,
  discount_amount numeric(12,2) not null check (discount_amount > 0),
  created_at timestamptz not null default now(),
  unique(order_id, coupon_id)
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.otp_verifications (
  id bigint generated by default as identity primary key,
  email text not null,
  code text not null,
  expires_at timestamptz not null,
  is_used boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.hero_slides enable row level security;
alter table public.campaigns enable row level security;
alter table public.coupons enable row level security;
alter table public.site_settings enable row level security;

create policy products_public_read on public.products for select to anon, authenticated using (true);
create policy categories_public_read on public.categories for select to anon, authenticated using (true);
create policy slides_public_read on public.hero_slides for select to anon, authenticated using (true);
create policy campaigns_public_read on public.campaigns for select to anon, authenticated using (true);
create policy coupons_member_read on public.coupons for select to authenticated using (is_active = true);
create policy settings_public_read on public.site_settings for select to anon, authenticated using (key in ('shipping','marquee'));

grant select on public.products, public.categories, public.hero_slides, public.campaigns, public.site_settings to anon, authenticated;
grant select on public.coupons to authenticated;
